### ISSUE TITLE
All requests return error 400

### ISSUE THREAD

**Issue by ReagentX** [GeneralMills/pytrends#231]
Every single request I make returns `ytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400.`

**Comment by hcaleman** [comment]
I am getting a similar response for my interest over time requests.  Early testing of my code over the past two days has worked with limited samples (one keyword at a time, looped over five companies).  I have now converted a production version of my code, including a random sleep of 10 - 60 secs, but every request returns errors on my local machine and two AWS instances.  

In request.py the defined query URL's (e.g.     INTEREST_OVER_TIME_URL = 'https://trends.google.com/trends/api/widgetdata/multiline')can not be resolved in my browser locally, via Tor, or on AWS machines.  Is this normal behavior, or does it indicate that something has changed on Google's side?  I am trying to access via alternative means to avoid issues of one particular IP being flagged.

**Comment by dabdada** [comment]
@ReagentX could you provide your call? If there is an unallowed parameter Google will return the 400 Bad request. You are basically only allowed to use parameters which are also available via google trends website. The most error resulting requests occurred on my side when first using this library have been a not acceptable timeframe parameter.

**Comment by ReagentX** [comment]
from pytrends.request import TrendReq
    pytrends = TrendReq(hl='en-US', tz=360, proxies = {'https': 'https://34.203.233.13:80'})
    kw_list = ["Blockchain"]
    pytrends.build_payload(kw_list, cat=0, timeframe='today 5-y', geo='', gprop='')

**Comment by dabdada** [comment]
I copied your code and this works without a problem for me with version 4.4.0. Could you please update if you are not running the newest version?

**Comment by theblackcat102** [comment]
I was able to replicate this issue when I change the timeframe from 'today 5-y' to 'today 1-y'
Is this some sort of google api limitation?

**Comment by danieljbruce** [comment]
I get the same problem as ReagentX.

**Comment by vbadita** [comment]
@danieljbruce which request did you use?

**Comment by SimeoW** [comment]
Dear future readers, adding a retry counter should fix this issue. This can be done as follows:
`pytrends = TrendReq(hl='en-US', tz=360, retries=10)`

Still, wrapping everything in a try/except block would be wise.

**Comment by shonexuyong** [comment]
Hi All, 

I am still having this issue even though i added the line suggested by SimeoW into the code. 

pytrends = TrendReq(hl='en-US', tz=360, retries=10, backoff_factor=0.5)

but i don;t know how to create a try/except block. 

any guidance would be much appreciated

**Comment by albertovpd** [comment]
it's really late for answering, but if someone needs it:
try:
    pytrends.build_payload(kw_list, cat=0, timeframe='today 5-y', geo='', gprop='',retries=10, backoff_factor=0.5)
    interest_over_time_df = pytrends.interest_over_time() 
    print(interest_over_time_df.head())
except:
    for e in kw_list:
        print(e, "couldn't be done")

in fact, the retries and backoff factor doesn't work for me

**Comment by phoebeqqe** [comment]
I tried @albertovpd's code, it returns all my keywords 'couldn't be done'.
My code is 
pytrend = TrendReq(hl='en')

try:
    pytrends.build_payload(searches, cat=0, timeframe='today 5-y', geo='US', gprop='')
    interest_over_time_df = pytrends.interest_over_time()
    print(interest_over_time_df.head())

except:
    for e in searches:
        print(e, "couldn't be done")

**Comment by albertovpd** [comment]
Hi there @phoebeqqe , 
At first sight I don't know what could be wrong, but maybe this insights can help:
- Maybe there is no relevant quota in the selected keywords, in the category 0.
- Maybe you got already blocked by the API, so everything you request today will return "couldn't be done". If this is the case, without the try/except you could get as return "error 500" or something like that.
- All the time I use in **timeframe** string type, I get error. So I used **timedelta libraries** to do the same in timestamp format. Here you can see how: 

https://github.com/albertovpd/socioeconomic_pytrends_gdelt_project/blob/master/cloud_function/request_pytrends.py

Hope this help you. I really love/hate (love mostly) pytrends, and using a simplistic try/except doesn't help debugging.
